"""Fix typo in Answer model(contetn)

Revision ID: 24712cfcd701
Revises: fe0d5833b8ad
Create Date: 2023-08-22 23:05:12.298597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24712cfcd701'
down_revision = 'fe0d5833b8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.drop_column('contetn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contetn', sa.TEXT(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
